app = "prosora-proxy"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  GHOST_HOST = "prosora-ghost.internal"
  GHOST_PORT = "2368"
  ACTIVITYPUB_HOST = "prosora-activitypub.internal"
  ACTIVITYPUB_PORT = "3000"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/_health"
    protocol = "http"

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1